import { days as fujiDays, type TripDay } from "@/lib/trip";

const flyOut: TripDay = {
  id: "x-fly",
  date: "Wed 18 Nov",
  city: "Bengaluru → air",
  title: "Night departure",
  pace: "Travel",
  spend: "Included in flights",
  plan: [
    "BLR 3 hours early. Gate-check the stroller.",
    "Cabin bag: passports, visas, hotel printouts, insurance, baby food, carrier.",
  ],
  eat: "Airport food.",
  move: "1-stop toward Tokyo.",
  baby: "Bassinet on the long sector.",
};

const tokyoArrive: TripDay = {
  id: "x-arrive",
  date: "Thu 19 Nov",
  city: "Narita → Asakusa",
  title: "Arrive slow — Senso-ji at dusk",
  pace: "Easy",
  spend: "Skyliner + simple dinner",
  plan: [
    "Keisei Skyliner to Ueno, then taxi/subway to Asakusa. No big sightseeing until check-in.",
    "Nap. Dusk loop of Senso-ji only. In by 18:30.",
  ],
  eat: "Nearby family restaurant. No Shinjuku tonight.",
  move: "Skyliner ¥2,570 adult.",
  baby: "Stroller in Asakusa, carrier in the temple crowd.",
};

const tokyoEasy: TripDay = {
  id: "x-tokyo-easy",
  date: "Fri 20 Nov",
  city: "Tokyo",
  title: "East Tokyo, no sprint",
  pace: "Relaxed",
  spend: "Food only",
  plan: [
    "Late start. Ueno Park or Sumida river. Skip paid towers unless the queue is nothing.",
    "14:00–16:00 hotel nap.",
  ],
  eat: "Hotel breakfast. Conveyor sushi lunch. Ramen dinner.",
  move: "Metro / walk.",
  baby: "Parks and covered malls.",
};

const tokyoShop: TripDay = {
  id: "x-shop",
  date: "Sat 21 Nov",
  city: "Tokyo",
  title: "Shopping day (own wallet)",
  pace: "Medium, with a nap",
  spend: "Core food only. Shopping extra.",
  plan: [
    "Shinjuku morning: Uniqlo/GU, Don Quijote tax-free.",
    "Then Shibuya or Ginza — not both plus Harajuku.",
    "Hotel by 17:30.",
  ],
  eat: "Depachika lunch. Cheap Asakusa dinner.",
  move: "Yamanote / Metro. Fold stroller at Shinjuku.",
  baby: "Split 2+2 if the baby melts down.",
};

const kyotoWest: TripDay = {
  id: "x-kyoto-w",
  date: "Kyoto west",
  city: "Kyoto",
  title: "Arashiyama only",
  pace: "Scenic, unhurried",
  spend: "Lunch + temple if you enter Tenryu-ji",
  plan: [
    "Bamboo grove early. River. Sit. No Fushimi today.",
    "Hotel by 15:30.",
  ],
  eat: "Hotel breakfast. River lunch with konbini fallback.",
  move: "Hankyu. Taxi back if the baby is done.",
  baby: "Stroller on the river path. Carrier in the grove.",
};

const kyotoEast: TripDay = {
  id: "x-kyoto-e",
  date: "Kyoto east",
  city: "Kyoto",
  title: "Kiyomizu and Gion, then stop",
  pace: "Walk, then rest",
  spend: "Two taxis + temple tickets",
  plan: [
    "Taxi to Kiyomizu. Walk down to Gion. Yasaka is free.",
    "Fushimi only if everyone is still kind — first gates only.",
  ],
  eat: "Picnic if queues exceed 15 minutes.",
  move: "Taxis for the hill.",
  baby: "Carrier on the slopes.",
};

const homeKix: TripDay = {
  id: "x-home",
  date: "Sat 28 Nov",
  city: "KIX → Bengaluru",
  title: "Fly home",
  pace: "Travel",
  spend: "Haruka + airport snacks",
  plan: [
    "Haruka to KIX (~75 min) unless the route ends in Namba — then Nankai Airport Express.",
    "Terminal 3 hours early.",
  ],
  eat: "Hotel breakfast. Airport ramen or onigiri.",
  move: "Reserved seats if the baby needs a sure seat.",
  baby: "Nappy after security.",
};

export const itineraries: Record<string, TripDay[]> = {
  "route-fuji": fujiDays,
  "route-hakone": [
    flyOut,
    tokyoArrive,
    tokyoEasy,
    tokyoShop,
    {
      id: "h-meiji",
      date: "Sun 22 Nov",
      city: "Tokyo",
      title: "Meiji Shrine, pack for Hakone",
      pace: "Easy",
      spend: "Food",
      plan: [
        "Meiji forest in the morning. Overflow shops on Omotesando only if Saturday was cut short.",
        "Send big bags to Kyoto. Pack a cabin bag for two Hakone nights.",
        "Confirm Romancecar seats for tomorrow (holiday).",
      ],
      eat: "Hotel breakfast. Early dinner.",
      move: "Metro to Harajuku.",
      baby: "Softest Tokyo day.",
    },
    {
      id: "h-go",
      date: "Mon 23 Nov",
      city: "Tokyo → Hakone",
      title: "Romancecar to Hakone-Yumoto",
      pace: "Transfer + easy evening",
      spend: "Romancecar + simple dinner",
      plan: [
        "Odakyu Romancecar from Shinjuku. Seated, luggage space, ~85 min.",
        "Check in near Hakone-Yumoto. Short village walk. No full loop today.",
        "Onsen: two adults rotate after the baby sleeps.",
      ],
      eat: "Hotel breakfast in Tokyo. Dinner at the inn or a yumoto ramen shop.",
      move: "Hakone Freepass from Shinjuku.",
      baby: "Train is easier than the Fuji highway bus.",
    },
    {
      id: "h-loop",
      date: "Tue 24 Nov",
      city: "Hakone",
      title: "Lake Ashi if the sky is kind",
      pace: "Slow",
      spend: "Freepass already bought",
      plan: [
        "One loop piece only: pirate ship or ropeway — not both plus Owakudani with a toddler on a holiday week.",
        "Fuji appears across the lake on a clear day. If cloud, stay in the onsen town.",
        "Nap. Pack.",
      ],
      eat: "Hotel breakfast. Simple lunch.",
      move: "Tozan train / bus included on Freepass.",
      baby: "Skip sulphur fields if windy. Carrier on steps.",
    },
    {
      id: "h-kyoto",
      date: "Wed 25 Nov",
      city: "Hakone → Kyoto",
      title: "Odawara Shinkansen",
      pace: "Transfer, then stop",
      spend: "Shinkansen reserved seats",
      plan: [
        "Local train to Odawara, then Hikari to Kyoto.",
        "Check in. Bags from Tokyo should be waiting. Do nothing else.",
      ],
      eat: "Ekiben on the train.",
      move: "Reserved Hikari. Not Nozomi if you ever held a JR Pass — you will not.",
      baby: "Longest day. Milk at Odawara.",
    },
    { ...kyotoWest, id: "h-west", date: "Thu 26 Nov" },
    { ...kyotoEast, id: "h-east", date: "Fri 27 Nov" },
    { ...homeKix, id: "h-home" },
  ],
  "route-oct16": [
    {
      ...flyOut,
      id: "n-fly",
      date: "Thu 15 Oct",
      city: "Bengaluru → air",
      title: "Night departure",
      plan: [
        "Leave BLR Thursday night 15 Oct so you land Tokyo Friday 16 Oct.",
        "Bassinet, passports, visas, carrier, 24 hours of baby food.",
      ],
    },
    {
      ...tokyoArrive,
      id: "n-arrive",
      date: "Fri 16 Oct",
    },
    {
      ...tokyoShop,
      id: "n-shop",
      date: "Sat 17 Oct",
      plan: [
        "Weekend shopping in Shinjuku, then Shibuya or Ginza — not both plus Harajuku.",
        "Hotel by 17:30. Do not go to Nikko this weekend — Irohazaka will be jammed.",
      ],
    },
    {
      id: "n-easy",
      date: "Sun 18 Oct",
      city: "Tokyo",
      title: "Meiji / Asakusa rest, pack for Nikko",
      pace: "Easy",
      spend: "Food",
      plan: [
        "Meiji Shrine or Ueno Park. Nap.",
        "Send big bags to the Kyoto hotel. Cabin bags only for Nikko.",
      ],
      eat: "Hotel breakfast. Early dinner.",
      move: "Metro / walk.",
      baby: "Do not add Disney.",
    },
    {
      id: "n-go",
      date: "Mon 19 Oct",
      city: "Tokyo → Nikko",
      title: "Spacia to Nikko — weekday on purpose",
      pace: "Transfer",
      spend: "Limited express tickets",
      plan: [
        "Tobu Spacia from Asakusa (closest to the hotel). Check in.",
        "Short walk to Shinkyo if energy remains. Highland air is cooler than Tokyo, not freezing.",
      ],
      eat: "Hotel with breakfast — Nikko evenings close early.",
      move: "Reserved limited express ~1h50.",
      baby: "Carrier at station stairs.",
    },
    {
      id: "n-shrine",
      date: "Tue 20 Oct",
      city: "Nikko",
      title: "Chuzenji colour — this is why you came in October",
      pace: "One mountain cluster",
      spend: "Bus + falls/shrine tickets",
      plan: [
        "This week (about 15–22 Oct) is peak around Lake Chuzenji and Kegon Falls. Go up in the morning.",
        "If the baby is done after the lake, skip Toshogu. If the lake is clouded in, do Toshogu instead — the town maples peak later, in early November.",
        "No second mountain. Nap. Pack.",
      ],
      eat: "Simple lunch near the lake or shrine, then hotel.",
      move: "World Heritage bus or a taxi. Do not self-drive Irohazaka.",
      baby: "Carrier. Cold at the lake — windproof. This is foliage, not snow.",
    },
    {
      id: "n-kyoto",
      date: "Wed 21 Oct",
      city: "Nikko → Kyoto",
      title: "Back through Tokyo Station, then Shinkansen",
      pace: "Long transfer",
      spend: "Train stack",
      plan: [
        "Morning train toward Tokyo / Ueno, then Hikari to Kyoto.",
        "Do not add a Tokyo activity on the way through. Check in and stop.",
      ],
      eat: "Ekiben.",
      move: "Spacia or JR + Tokaido Shinkansen, reserved seats.",
      baby: "Screens and milk. The hard day.",
    },
    { ...kyotoWest, id: "n-west", date: "Thu 22 Oct" },
    { ...kyotoEast, id: "n-east", date: "Fri 23 Oct" },
    {
      id: "n-buffer",
      date: "Sat 24 Oct",
      city: "Kyoto",
      title: "Buffer / Nishiki / laundry",
      pace: "Easy",
      spend: "Food and last gifts",
      plan: [
        "Kyoto is still mostly green in mid-October. Do not hunt maples. Use this day for a slow market walk or a rest.",
        "Pack. Confirm Haruka time.",
      ],
      eat: "Hotel breakfast. Whatever the group wants.",
      move: "Walk / subway.",
      baby: "Protect sleep before the flight.",
    },
    {
      ...homeKix,
      id: "n-home",
      date: "Sun 25 Oct",
    },
  ],
  "route-nikko": [
    {
      ...flyOut,
      id: "nov-n-fly",
      date: "First-week November — set your own Wed night",
      plan: [
        "Use this route only in the first week of November, not 16 October.",
        "Same cabin rules: bassinet, passports, carrier.",
      ],
    },
    { ...tokyoArrive, id: "nov-n-arrive", date: "Day 1" },
    { ...tokyoShop, id: "nov-n-shop", date: "Day 2 — shopping so Nikko stays quiet" },
    {
      id: "nov-n-easy",
      date: "Day 3",
      city: "Tokyo",
      title: "Ueno / Asakusa rest day",
      pace: "Easy",
      spend: "Food",
      plan: ["Park, museum only if weather is bad, nap, pack for Nikko."],
      eat: "Hotel breakfast.",
      move: "Walk / metro.",
      baby: "Do not add Disney.",
    },
    {
      id: "nov-n-go",
      date: "Day 4",
      city: "Tokyo → Nikko",
      title: "Spacia to Nikko",
      pace: "Transfer",
      spend: "Limited express tickets",
      plan: [
        "Tobu Spacia from Asakusa, or JR via Utsunomiya. Check in.",
        "Short walk only. Highland air is colder than Tokyo.",
      ],
      eat: "Hotel with breakfast — Nikko evenings close early.",
      move: "Reserved limited express.",
      baby: "Carrier at the station stairs.",
    },
    {
      id: "nov-n-shrine",
      date: "Day 5",
      city: "Nikko",
      title: "Toshogu morning, then stop",
      pace: "One cluster",
      spend: "Shrine tickets",
      plan: [
        "Toshogu at opening. Stairs — no stroller inside the core.",
        "Lake Chuzenji only if the baby is still happy. Town maples are likelier in early November than at the lake.",
      ],
      eat: "Simple lunch near the shrine, then rest.",
      move: "World Heritage bus or taxi between clusters.",
      baby: "This is the frost/snow-chance day, not a ski day.",
    },
    {
      id: "nov-n-kyoto",
      date: "Day 6",
      city: "Nikko → Kyoto",
      title: "Back toward Tokyo Station, then Shinkansen",
      pace: "Long transfer",
      spend: "Train stack",
      plan: ["Leave morning. Do not add a Tokyo activity on the way through."],
      eat: "Ekiben.",
      move: "Spacia or JR + Tokaido Shinkansen.",
      baby: "Screens and milk. This is the hard day.",
    },
    { ...kyotoWest, id: "nov-n-west", date: "Day 7" },
    { ...kyotoEast, id: "nov-n-east", date: "Day 8" },
    { ...homeKix, id: "nov-n-home", date: "Day 9" },
  ],
  "route-osaka": [
    flyOut,
    tokyoArrive,
    tokyoEasy,
    tokyoShop,
    {
      id: "o-meiji",
      date: "Sun 22 Nov",
      city: "Tokyo",
      title: "Meiji, pack, send bags to Kyoto",
      pace: "Easy",
      spend: "Food",
      plan: [
        "Meiji Shrine. Last Tokyo shops only if needed.",
        "Yamato the big bags to the Kyoto hotel.",
      ],
      eat: "Hotel breakfast.",
      move: "Metro.",
      baby: "Soft day before the holiday Shinkansen.",
    },
    {
      id: "o-shink",
      date: "Mon 23 Nov",
      city: "Tokyo → Kyoto",
      title: "Holiday Shinkansen — seats already reserved",
      pace: "Transfer, then stop",
      spend: "Reserved Hikari × 4",
      plan: [
        "Do not try Kyoto temples today. Holiday crowds.",
        "Check in. Walk Nishiki 20 minutes at most.",
      ],
      eat: "Ekiben. Light Kyoto dinner.",
      move: "Tokyo Station. Stroller fold on the platform.",
      baby: "Book the first train you can sit together on.",
    },
    { ...kyotoWest, id: "o-west", date: "Tue 24 Nov" },
    { ...kyotoEast, id: "o-east", date: "Wed 25 Nov" },
    {
      id: "o-namba",
      date: "Thu 26 Nov",
      city: "Kyoto → Osaka",
      title: "Short hop to Namba",
      pace: "Easy transfer",
      spend: "JR/Hankyu + Dotonbori food",
      plan: [
        "Late morning train (~30–40 min). Check in Namba.",
        "Kuromon walk. Dotonbori lights after the nap. Carrier in the crowd.",
      ],
      eat: "Takoyaki to share, then a sit-down okonomiyaki.",
      move: "JR or Hankyu. Walk from Namba.",
      baby: "This is the shopping-and-food city, not a mountain.",
    },
    {
      id: "o-aqua",
      date: "Fri 27 Nov",
      city: "Osaka",
      title: "Kaiyukan or covered shopping",
      pace: "Indoor option",
      spend: "Aquarium tickets if you go",
      plan: [
        "Kaiyukan timed entry, or Shinsaibashi shops if rain/energy is low.",
        "No USJ. Pack for KIX.",
      ],
      eat: "Conveyor sushi or mall food.",
      move: "Chuo Line to Osakako for the aquarium.",
      baby: "Aquarium is the indoor memory. Changing rooms exist.",
    },
    {
      ...homeKix,
      id: "o-home",
      city: "Namba → KIX",
      title: "Nankai Airport Express",
      move: "Nankai Airport Express 44 min, ¥970. Not the Haruka.",
    },
  ],
  "route-kanazawa": [
    flyOut,
    tokyoArrive,
    tokyoShop,
    {
      id: "k-go",
      date: "Sun 22 Nov",
      city: "Tokyo → Kanazawa",
      title: "Hokuriku Shinkansen",
      pace: "Transfer, then stop",
      spend: "Reserved Shinkansen ~2.5h",
      plan: [
        "Morning train from Tokyo Station. Check in. No temples today.",
        "Send leftover Tokyo bags onward to Kyoto if you did not already.",
      ],
      eat: "Ekiben. Quiet Kanazawa dinner.",
      move: "Kagayaki or Hakutaka reserved.",
      baby: "Seated the whole way — kinder than a bus.",
    },
    {
      id: "k-garden",
      date: "Mon 23 Nov",
      city: "Kanazawa",
      title: "Kenrokuen at opening",
      pace: "Slow garden day",
      spend: "Garden tickets",
      plan: [
        "Holiday morning at Kenrokuen before tour buses. Skip the castle keep.",
        "Higashi Chaya walk after the nap, 45 minutes, then hotel.",
      ],
      eat: "Hotel breakfast. Market or teahouse lunch.",
      move: "Bus or taxi from the station hotel.",
      baby: "Paths are manageable. Cold air — layers.",
    },
    {
      id: "k-market",
      date: "Tue 24 Nov",
      city: "Kanazawa",
      title: "Omicho market and crafts",
      pace: "Easy",
      spend: "Gold-leaf souvenirs extra",
      plan: [
        "Omicho in the morning. One craft shop. Nap. No extra town.",
      ],
      eat: "Market sushi / grilled seafood, then simple dinner.",
      move: "Walk if the hotel is central.",
      baby: "This is why this route exists — a quiet middle.",
    },
    {
      id: "k-thunder",
      date: "Wed 25 Nov",
      city: "Kanazawa → Kyoto",
      title: "Thunderbird to Kyoto",
      pace: "Transfer, then stop",
      spend: "Limited express",
      plan: ["Late morning train. Kyoto check-in. Rest."],
      eat: "Ekiben.",
      move: "Thunderbird to Kyoto Station.",
      baby: "Second long sit. Worth it for the slow cities on either side.",
    },
    { ...kyotoWest, id: "k-west", date: "Thu 26 Nov" },
    { ...kyotoEast, id: "k-east", date: "Fri 27 Nov" },
    { ...homeKix, id: "k-home" },
  ],
};
